### ISSUE TITLE
Check compatibility on php 7

### ISSUE THREAD

**Issue by Yexiaoxing** [AOSC-Dev/community-portal#6]
Our new server is deployed with php 7 (phpng)
Please all guys, check if there is anything going wrong, including techbase ( originally wiki-dev (.

**Comment by biergaizi** [comment]
What? *pgp*ng? When did the encryption software become a web server?

**Comment by Yexiaoxing** [comment]
The fucking input method....
It must be phpng.

**Comment by biergaizi** [comment]
PHPNG is a new major version of PHP, it breaks the backward compatibility, and it is still under heavy development. I think nobody should deploy it on the production server.

Yes, it is important to check the compatibility of the new version, but it is too early to do it now. There is no any release version, even RC version for PHP 7.

Such work should be started after the first RC version of PHP 7.

**Comment by biergaizi** [comment]
If you need performance, you should try HHVM instead of PHP 7 for now.

**Comment by Yexiaoxing** [comment]
@biergaizi You are right. Issue is delayed and our server will remain php 5.6.5.
